### ISSUE TITLE
Need support for getting assignable groups for a project and assigning a group to a project

### ISSUE THREAD

**Issue by eric-isakson** [blackducksoftware/blackduck-common#222]
Had to work around the fact that there is no API or HubResponse object for this endpoint:

GET /api/projects/{projectId}/assignable-usergroups

Which should be available on the ProjectService

Which is needed to get the usergroup URI to give to this endpoint:

POST /api/projects/{projectId}/usergroups

Which should also be supported by the ProjectService

What I needed in my project was the ability to ensure groups are assigned to a project, so given a project name and list of group names, if the group is not assigned to project, add it.

**Comment by eric-isakson** [comment]
I'm open to other ideas here if this is not the intent of these endpoints. I didn't see any developer doc to help me understand which ones to use when, so I'm basically just exploring the API described in the REST API Developers Guide linked off the tools page.

I also tried using the UserGroupService but I had to access the UserGroupView._meta.href property to get the uri of the group. Is that fair game? Many of the scripting languages I've worked in before prefixed variables with _ to denote privacy when they needed to expose something in the public API that wasn't really intended to be public but there was no other language construct to protect the API.

**Comment by gkillough** [comment]
Hi @eric-isakson, 

You are correct that there should be a method to access assignable-usergroups from the ProjectService. There seem to be a few links that we have not yet added to [hub-common-api](https://github.com/blackducksoftware/hub-common-api). We will work on adding those.

We do however have a HubResponse for the object returned from that endpoint: 
com.synopsys.integration.blackduck.api.generated.view.AssignedUserView 

For getting an href from a HubView (which contains the ResourceMetadata "_meta"), please use this method found in the HubService class: getHref(hubViewInstance).

You can also use HubService to access links that might currently be missing from the API: 
    HubService myHubService = . . . ;
    boolean hasLink = myHubService.hasLink(hubProjectView, "missingLinkName"); 
    if (hasLink) {
        String linkUrl = myHubService.getFirstLink(hubProjectView, "missingLinkName");
        Response responseFromLink = myHubService.executeGetRequest(linkUrl);
    }
    // Alternatively: 
    LinkMultipleResponses<AssignedUserView> missingLinkResponse = new LinkMultipleResponses<>("missingLinkName", AssignedUserView.class);
    List<AssignedUserView> foundViews = myHubService.getAllResponses(hubProjectView, missingLinkResponse);

For more examples, please look [here](https://github.com/blackducksoftware/hub-common/blob/master/src/test/groovy/com/synopsys/integration/blackduck/comprehensive/ComprehensiveCookbookTestIT.java).

**Comment by eric-isakson** [comment]
Thank you for the tip on using hubService.getHref(hubView), I've changed my code to use that rather than directly accessing the _meta field.

I ended up using the UserGroupService to get each group by name, get its href and then using:

        final String projectUserGroupsUrl = hubService.getFirstLink(project, ProjectView.USERGROUPS_LINK);

        final String json = "{\"group\": \"" + groupUri + "\"}";
        final Request request = RequestFactory.createCommonPostRequestBuilder(json).uri(projectUserGroupsUrl).mimeType("application/json").build();
        hubService.executePostRequestAndRetrieveURL(request);

to assign the group to the project. I expected based on the name of this endpoint

GET /api/projects/{projectId}/assignable-usergroups

That I would get a list of objects that would have sufficient information for me to then make the necessary POST request to assign the groups whose names matched my list of group names. The rest endpoint does that but the java library needs to catch up. AssignedUserView is for users, I'm working with groups so unless the assignable-usergroups endpoint needs a different HubResponse object, I'm fine working with the UserGroupView object.

Ideally, I would like to have an API like:

List<UserGroupView> projectService.getAssignableUserGroupsForProject(String projectName)
List<UserGroupView> projectService.getAssignableUserGroupsForProject(ProjectView project)
void projectService.addUserGroupsToProject(String projectName, List<String> groupNames)
void projectService.addUserGroupToProject(String projectName, String groupName)
void projectService.addUserGroupsToProject(ProjectView project, List<UserGroupView> groups)
void projectService.addUserGroupToProject(ProjectView project, UserGroupView group)

There is also a need for similar APIs for assigning users. For completeness, the inverse for removing users and groups should exist although I don't have need for those right now.

**Comment by ekerwin** [comment]
This is great stuff, @eric-isakson, and we'll see what we can do. Unfortunately, the java library is not maintained in lock-step with the REST API - they are developed on very different schedules with completely different teams. In the java library's current form, it will most likely never be up to date with the REST API. If that is your requirement, I would encourage you to use HubService even more than you are now and abandon ProjectService.

Typically, hub-common receives updates when an integration needs a new API or link.

I believe ProjectService is currently too large to be well-supported - your recommended changes show this even clearer. I suspect we will want a ProjectGroupService to support the combination of projects and groups, but we'll figure this out in the coming weeks/months.

Thanks so much for your feedback!
