### ISSUE TITLE
Java API: About mediaTypeDiscovery

### ISSUE THREAD

**Issue by chanrai** [blackducksoftware/blackduck-common#289]
The Java API that the previously created  is no longer work after 45.0.6.  I get the following error when connecting to the Black Duck Hub.

Exception in thread "main" java.lang.NoSuchMethodError: com.synopsys.integration.blackduck.api.generated.discovery.MediaTypeDiscovery.determineMediaType(Ljava/lang/String;)Ljava/lang/String;

It seems that MediaTypeDiscovery has a new method added. 
Why is it needed to connect to the Black Duck Hub?
Could you tell me how to use this method for connect hub.

Thank you!

**Comment by ekerwin** [comment]
I will try and create a test soon that will show you how we'd recommend using the library. For now, I would suggest using BlackDuckServerConfigBuilder to create a BlackDuckServerConfig, which you can use to create a BlackDuckServicesFactory.

With that factory, you can create the various services we expose to connect to Black Duck, and using their api's should (hopefully!) be clear enough.

Is there a particular problem you are trying to solve?

Thanks for reaching out!

**Comment by chanrai** [comment]
>I will try and create a test soon that will show you how we'd recommend using the library

I'm sorry for your inconvenience but thank you for your cooperation.

>suggest using BlackDuckServerConfigBuilder to create a BlackDuckServerConfig, 
>which you can use to create a >BlackDuckServicesFactory.
>With that factory, you can create the various services we expose to connect to Black Duck, 

Thank you for the information. I will try it.

Thanks and Best regards.

**Comment by chanrai** [comment]
@ekerwin

When I run the API with BlackDuckServerConfigBuilder, such as
 
`blackDuckServerConfigBuilder= new BlackDuckServerConfigBuilder();` 

The following error has occurred.

`Exception in thread "main" java.lang.NoClassDefFoundError: com/synopsys/integration/rest/support/UrlSupport
	at com.synopsys.integration.blackduck.service.BlackDuckServicesFactory.createDefaultUrlSupport(BlackDuckServicesFactory.java:91)
	at com.synopsys.integration.blackduck.configuration.BlackDuckServerConfigBuilder.<init>(BlackDuckServerConfigBuilder.java:77)`

And I found in the "integration-rest" API, The follow file did not exist at version 5.0.0

[(https://github.com/blackducksoftware/integration-rest/tree/master/src/main/java/com/synopsys/integration/rest/support/UrlSupport.java) ]

What should I do for fix it?

Thanks and Best regards.

**Comment by ekerwin** [comment]
For version 49.1.0, which is the latest:
```
BlackDuckServerConfigBuilder` blackDuckServerConfigBuilder = new BlackDuckServerConfigBuilder();
blackDuckServerConfigBuilder.setUrl("https://blackduck_server");
blackDuckServerConfigBuilder.setUsername("username");
blackDuckServerConfigBuilder.setPassword("secret_password");

BlackDuckServerConfig blackDuckServerConfig = blackDuckServerConfigBuilder.build();
IntLogger logger = new PrintStreamLogger(System.out, LogLevel.DEBUG);
BlackDuckServicesFactory blackDuckServicesFactory = blackDuckServerConfig.createBlackDuckServicesFactory(logger);

```
With a BlackDuckServicesFactory, you can create the various services you might need. And if you want just a low level api client, you can use the BlackDuckService:
blackDuckServicesFactory.getBlackDuckService();

As for why media type discovery is needed, Black Duck wants certain values set for the HTTP Accept header and the media type discovery class is in charge of determining the correct media type value to use in that header.

**Comment by ekerwin** [comment]
It looks like your issues are from trying to include different versions of the libraries. You should only need to include the single blackduck-common 49.1.0 jar dependency. If you try and include old versions of the other integration libraries, you can get the errors you are seeing. If you are able to just include blackduck-common and are still unable to use the library, please re-open this and we can get you some more direct support. Thanks!
