### ISSUE TITLE
blackduck-common 63.0.2 unable to satisfy dependency on bdio2 

### ISSUE THREAD

**Issue by sstafford** [blackducksoftware/blackduck-common#378]
I am trying to update the dependencies in my java application from blackduck-common 50.3.0 to 63.0.2.  However, my gradle build fails because it is unable to find the bdio2 transitive dependency:

   > Could not find com.blackducksoftware.bdio:bdio2:3.2.3.
     Required by:
         project : > com.synopsys.integration:blackduck-common:63.0.2

Could you tell me what Maven repository the bdio2 library is published to so that I can resolve this dependency?

**Comment by DanaMaxfield** [comment]
The repository is the Synopsys public Artifactory instance "https://sig-repo.synopsys.com/bds-bdio-release"

[https://github.com/blackducksoftware/blackduck-common/blob/63.0.2/build.gradle#L23-L25](https://github.com/blackducksoftware/blackduck-common/blob/63.0.2/build.gradle#L23-L25)
